[dev]
  command = "npm run start"
  targetPort = 5200
  port = 8888 
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist/todo/browser"


[[redirects]]
  from = "/*"
  to = "/.netlify/v1/functions/ssr"
  status = 200
  force = true