export enum UPDATE_EMAIL_CODES {
  EMAIL_UPDATED = 'EMAIL_UPDATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  MISMATCH_TOKEN = 'MISMATCH_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UPDATE_ERROR = 'UPDATE_ERROR'
}
