export const PROFILE_STATUS = {
  LINK: {
    INITIAL: 'INITIAL',
    SENDING: 'SENDING',
    SENT: 'SENT'
  },
  EMAIL: {
    INITIAL: 'INITIAL',
    CHANGE: 'CHANGE',
    VERIFY: 'VERIFY',
    VERIFIED: 'VERIFIED',
    CHECKING: 'CHECKING',
    VALID: 'VALID',
    INVALID: 'INVALID',
    CHECKED: 'CHECKED',
    FAILED: 'FAILED',
    SENDING: 'SENDING',
    SENT: 'SENT'
  },
  PASSWORD: {
    INITIAL: 'INITIAL',
    SENDING: 'SENDING',
    SENT: 'SENT',
    FAILED: 'FAILED',
    CHANGED: 'CHANGED',
    VERIFIED: 'VERIFIED',
    MISMATCHED: 'MISMATCHED'
  }
}